NUM_COMMENTS = 5

NFL_FLAIRS = {
    'bears': 'Bears',
    'bengals': 'Bengals',
    'bills': 'Bills',
    'broncos': 'Broncos',
    'browns': 'Browns',
    'buccaneers': 'Buccaneers',
    'cardinals': 'Cardinals',
    'chargers': 'Chargers',
    'chiefs': 'Chiefs',
    'colts': 'Colts',
    'cowboys': 'Cowboys',
    'dolphins': 'Dolphins',
    'eagles': 'Eagles',
    'falcons': 'Falcons',
    'fortyniners': '49ers',
    'giants': 'Giants',
    'jaguars': 'Jaguars',
    'jets': 'Jets',
    'lions': 'Lions',
    'packers': 'Packers',
    'panthers': 'Panthers',
    'patriots': 'Patriots',
    'raiders': 'Raiders',
    'rams': 'Rams',
    'ravens': 'Ravens',
    'redskins': 'Redskins',
    'saints': 'Saints',
    'seahawks': 'Seahawks',
    'steelers': 'Steelers',
    'texans': 'Texans',
    'titans': 'Titans',
    'vikings': 'Vikings'}

NBA_FLAIRS = {
    '76ers': '76ers',
    'Bucks': 'Bucks',
    'Bullets': 'Wizards',
    'Bulls': 'Bulls',
    'Cavaliers': 'Cavaliers',
    'CavaliersBandwagon': 'Cavaliers',
    'Celtics': 'Celtics',
    'ChaHornets': 'Hornets',
    'Clippers': 'Clippers',
    'Grizzlies': 'Grizzlies',
    'Hawks': 'Hawks',
    'Heat': 'Heat',
    'HeatBandwagon': 'Heat',
    'Jazz': 'Jazz',
    'Kings': 'Kings',
    'KnickerBockers': 'Knicks',
    'Knicks': 'Knicks',
    'Lakers': 'Lakers',
    'Magic': 'Magic',
    'Mavs': 'Mavericks',
    'MinnLakers': 'Lakers',
    'Nets': 'Nets',
    'Nuggets': 'Nuggets',
    'Pacers': 'Pacers',
    'Pelicans': 'Pelicans',
    'Pistons': 'Pistons',
    'Raptors': 'Raptors',
    'RaptorsBandwagon': 'Raptors',
    'Rockets': 'Rockets',
    'Spurs': 'Spurs',
    'Suns': 'Suns',
    'Supersonics': 'Supersonics',
    'Thunder': 'Thunder',
    'ThunderBandwagon': 'Thunder',
    'Timberwolves': 'Timberwolves',
    'TrailBlazers': 'Trail Blazers',
    'VanGrizzlies': 'Grizzlies',
    'Warriors': 'Warriors',
    'WarriorsBandwagon': 'Warriors',
    'Wizards': 'Wizards'}

FLAIRS = {
    'nba':NBA_FLAIRS,
    'nfl':NFL_FLAIRS
}